import { Project } from '@/types/project';

/**
 * Generates the Integration Checklist — the step-by-step verification
 * that ensures every piece of the framework is properly connected.
 *
 * Three checklists:
 * 1. For any project (core setup)
 * 2. For multi-agent setups
 * 3. For knowledge-heavy projects
 */
export function generateIntegrationChecklist(project: Project): string {
  const moduleCount = project.phases.length;
  const hasMultipleAgents = true; // Framework always supports multi-agent

  return `# Integration Checklist — ${project.name}

> Use this checklist to verify that every piece of the AI development framework
> is properly connected. Work through it top-to-bottom after initial setup.

---

## Core Setup (Any Project)

- [ ] Create \`.claude/CLAUDE.md\` with project overview, commands, task protocol, structure
- [ ] Create \`.claude/rules/\` with at minimum:
  - [ ] \`code-style.md\` — TypeScript conventions, naming, imports
  - [ ] \`database.md\` — Common columns, RLS pattern, migration rules
  - [ ] \`task-process.md\` — Task protocol, phase addition guide
  - [ ] \`architecture.md\` — Feature-first organization, data flow
  - [ ] \`testing.md\` — What to test, what not to test
- [ ] Create \`knowledge/\` directory structure:
  \`\`\`
  knowledge/
  ├── prod.md
  ├── PRD.json
  ├── skills.md
  ├── tools.md
  ├── workflows.md
  ├── skills/
  │   ├── shared/
  │   └── [module]/
  ├── tools/
  │   ├── db/
  │   ├── api/
  │   ├── ui/
  │   └── automation/
  └── workflows/
      ├── shared/
      └── [module]/
  \`\`\`
- [ ] Create \`knowledge/prod.md\` — Master domain reference (all ${moduleCount} modules)
- [ ] Create index files:
  - [ ] \`knowledge/skills.md\` — Skill index
  - [ ] \`knowledge/tools.md\` — Tool index
  - [ ] \`knowledge/workflows.md\` — Workflow index
- [ ] Create \`knowledge/PRD.json\` — Task dependency graph
- [ ] Run the \`project_tasks\` migration (database setup)
- [ ] Seed your Phase 1 tasks
- [ ] Add the project tracker UI (hook + components + page)
- [ ] Register \`/project-tracker\` route

---

## Multi-Agent Setup

- [ ] Create \`AGENTS.md\` at repo root for secondary agent
- [ ] Set \`assigned_to\` CHECK constraint with all agent names
- [ ] Assign tasks by specialization:
  - Agent-1 (Claude Code): Architecture, complex UI, hooks/API, AI agents
  - Agent-2 (Codex): Database migrations, RLS, audit triggers, CRUD
- [ ] Test that each agent can query its own task queue:
  \`\`\`sql
  SELECT task_code, title FROM project_tasks
  WHERE status = 'pending' AND assigned_to = 'agent-1'
  ORDER BY priority DESC LIMIT 1;
  \`\`\`

---

## Knowledge-Heavy Setup

- [ ] Create skill files for each module:
${project.phases.map(p => `  - [ ] \`knowledge/skills/${p.name.toLowerCase().replace(/\s+/g, '-')}/${p.name.toLowerCase().replace(/\s+/g, '-')}.skill.md\``).join('\n')}
- [ ] Create tool files for each entity:
  - [ ] DB tools: \`knowledge/tools/db/[entity]-crud.tool.md\`
  - [ ] API tools: \`knowledge/tools/api/[function].tool.md\`
  - [ ] UI tools: \`knowledge/tools/ui/[component].tool.md\`
  - [ ] Automation tools: \`knowledge/tools/automation/[pipeline].tool.md\`
- [ ] Create workflow files for each process:
  - [ ] Shared workflows: \`knowledge/workflows/shared/[process].workflow.md\`
  - [ ] Module workflows: \`knowledge/workflows/[module]/[workflow].workflow.md\`
- [ ] Reference knowledge files in task \`wat_references\` arrays
- [ ] Keep index files (\`skills.md\`, \`tools.md\`, \`workflows.md\`) up to date

---

## Verification Commands

Run these to confirm the system is operational:

\`\`\`bash
# 1. Type check
npx tsc --noEmit

# 2. Build
npm run build

# 3. Lint
npm run lint

# 4. Push database migration
npx supabase db push

# 5. Verify tasks exist
# (run in Supabase SQL editor or psql)
SELECT count(*), status FROM project_tasks GROUP BY status;

# 6. Verify levels exist
SELECT * FROM project_levels ORDER BY level;
\`\`\`

---

## Greenfield Quick Start

\`\`\`bash
# 1. Scaffold
npm create vite@latest my-project -- --template react-ts
cd my-project

# 2. Create framework structure
mkdir -p .claude/rules
mkdir -p knowledge/{skills/shared,tools/db,tools/api,tools/ui,tools/automation,workflows/shared}

# 3. Fill in templates (generated by VibePM)
# 4. Run project_tasks migration
# 5. Seed Phase 1 tasks
# 6. Add tracker UI
# 7. Start working — agents follow the task protocol from here
\`\`\`

---

## Brownfield Quick Start

\`\`\`bash
# 1. Create framework structure
mkdir -p .claude/rules
mkdir -p knowledge/{skills/shared,tools/db,tools/api,tools/ui,tools/automation,workflows/shared}

# 2. Document YOUR EXISTING project (don't invent new conventions)
# 3. Create Phase 0 migration marking existing work as complete:

# Phase 0 Brownfield Backfill:
# INSERT INTO project_tasks (task_code, title, phase, category,
#   assigned_to, priority, xp_reward, status, progress_pct, completed_at)
# VALUES
#   ('P0-01', 'Initial project setup', 'phase0', 'infra',
#    'human', 100, 15, 'completed', 100, now()),
#   ('P0-02', 'Auth system', 'phase0', 'feature',
#    'human', 95, 25, 'completed', 100, now())
# ON CONFLICT (task_code) DO NOTHING;

# 4. Seed your NEXT phase as pending tasks
# 5. Start working
\`\`\`

---

## Scaling Reference

| Project Size | Knowledge Files | Tasks | Phases | Agents |
|-------------|----------------|-------|--------|--------|
| **Small** (1 module, solo) | 3–5 | 10–20 | 1–2 | 1 |
| **Medium** (5 modules, 1 team) | 15–30 | 30–80 | 3–6 | 1–2 |
| **Large** (15+ modules, multi-team) | 50–100 | 100–200 | 8–15 | 2–3 |
| **Enterprise** (30+ modules) | 100+ | 200+ | 15+ | 3+ |

The system scales linearly — more modules means more knowledge files and tasks, but the framework stays the same.
`;
}
