import { Project } from '@/types/project';

export function generateSetupGuide(project: Project): string {
  const taskCount = project.tasks.length;
  const phaseCount = project.phases.length;
  const phases = project.phases.map(p => `- **${p.name}**: ${p.description}`).join('\n');

  return `# ${project.name} — Setup Guide

> Generated by [VibePM](https://github.com/your-org/vibepm)

## Prerequisites

- [Supabase](https://supabase.com) account (free tier works)
- [VS Code](https://code.visualstudio.com/) with one of:
  - [Claude Code](https://claude.ai/code) (Anthropic)
  - [Codex](https://openai.com/codex) (OpenAI)
- Node.js 18+

## Quick Start

### 1. Create a Supabase Project

1. Go to [supabase.com/dashboard](https://supabase.com/dashboard)
2. Click **New Project**
3. Note your **Project URL** and **anon key** from Settings → API

### 2. Run the Database Migration

Open the **SQL Editor** in your Supabase dashboard and paste the contents of:

\`\`\`
supabase/migrations/00001_project_tasks.sql
\`\`\`

This creates:
- \`project_tasks\` table (${taskCount} tasks across ${phaseCount} phases)
- \`project_levels\` table (15 XP levels for gamification)
- RLS policies for authenticated access
- Indexes for fast queries

### 3. Deploy the Edge Function

Install the Supabase CLI if you haven't:

\`\`\`bash
npm install -g supabase
\`\`\`

Link your project and deploy:

\`\`\`bash
supabase login
supabase link --project-ref YOUR_PROJECT_REF
supabase functions deploy agent-tasks
\`\`\`

### 4. Add Your API Keys as Secrets

\`\`\`bash
# Required for AI agents to authenticate
supabase secrets set SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# Required: Your AI provider API key (OpenAI, Anthropic, Google, etc.)
supabase secrets set AI_API_KEY=your-ai-api-key

# Optional: Custom AI gateway URL and model (defaults to OpenAI gpt-4o)
supabase secrets set AI_GATEWAY_URL=https://api.openai.com/v1/chat/completions
supabase secrets set AI_MODEL=gpt-4o
\`\`\`

### 5. Configure Your AI Agent

Create a \`.env\` file in your project root:

\`\`\`env
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-anon-key
\`\`\`

Then point your agent (Claude Code or Codex) at the agent-tasks endpoint:

\`\`\`
POST https://your-project.supabase.co/functions/v1/agent-tasks
Authorization: Bearer <user-jwt>
Content-Type: application/json

{"action": "next", "agent_id": "claude-code"}
\`\`\`

## Agent API Reference

| Action | Description |
|--------|-------------|
| \`next\` | Get highest-priority pending task |
| \`claim\` | Atomically claim a task (race-safe) |
| \`complete\` | Mark task completed (awards XP) |
| \`block\` | Mark task blocked with notes |
| \`status\` | Get overall progress stats |
| \`list\` | List tasks with filters |

### Example Agent Loop

\`\`\`bash
# 1. Get next task
curl -X POST $SUPABASE_URL/functions/v1/agent-tasks \\
  -H "Authorization: Bearer $JWT" \\
  -d '{"action": "next", "agent_id": "claude-code"}'

# 2. Claim it
curl -X POST $SUPABASE_URL/functions/v1/agent-tasks \\
  -H "Authorization: Bearer $JWT" \\
  -d '{"action": "claim", "task_code": "P1-01", "agent_id": "claude-code"}'

# 3. Do the work...

# 4. Complete it
curl -X POST $SUPABASE_URL/functions/v1/agent-tasks \\
  -H "Authorization: Bearer $JWT" \\
  -d '{"action": "complete", "task_code": "P1-01", "notes": "Implemented feature X"}'
\`\`\`

## Project Phases

${phases}

## Tracker UI

This export includes portable tracker components in the \`tracker/\` folder:
- \`useProjectTasks.ts\` — data hook (Supabase + TanStack Query)
- \`ProgressRing.tsx\` — circular progress indicator
- \`TaskCard.tsx\` — individual task display
- \`ProjectTasksPage.tsx\` — full tracker page with filters

To use them, copy into your project and update the Supabase client import path.

## Live Updates

The tracker supports real-time updates. As your AI agents complete tasks,
the tracker UI updates automatically via Supabase Realtime.

---

**Stack**: ${project.stack.framework} · ${project.stack.language} · ${project.stack.backend}
**Tasks**: ${taskCount} across ${phaseCount} phases
**Generated**: ${new Date().toISOString().split('T')[0]}
`;
}
