import { useState, useRef, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Plus, Trash2, ArrowRight, ArrowLeft, Sparkles, Loader2, Check, AlertCircle, Upload, FileText, X } from "lucide-react";
import { BrainDumpEntry, Project } from "@/types/project";
import * as store from "@/lib/store";
import { analyzeProject, generateTasks, AnalysisResult, GeneratedTask } from "@/lib/ai-generate";
import { generateConfigFromTemplates } from "@/lib/generate-from-templates";
import { useToast } from "@/hooks/use-toast";
import { useProjectTasks } from "@/hooks/useProjectTasks";

type WizardStep = 1 | 2 | 3 | 4;

interface StepStatus {
  analyze: 'idle' | 'loading' | 'done' | 'error';
  tasks: 'idle' | 'loading' | 'done' | 'error';
  knowledge: 'idle' | 'loading' | 'done' | 'error';
  config: 'idle' | 'loading' | 'done' | 'error';
}

const DEFAULT_STACK: Project['stack'] = {
  framework: 'Unknown',
  language: 'Unknown',
  buildTool: 'Unknown',
  backend: 'Unknown',
  ui: 'Unknown',
  stateManagement: 'Unknown',
  forms: 'Unknown',
  validation: 'Unknown',
};

export default function NewProject() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { seedTasks } = useProjectTasks();
  const [step, setStep] = useState<WizardStep>(1);
  const [entries, setEntries] = useState<BrainDumpEntry[]>([
    { id: crypto.randomUUID(), title: "Main Ideas", content: "" },
  ]);
  const [projectName, setProjectName] = useState("");
  const [projectDesc, setProjectDesc] = useState("");

  // AI processing state
  const [stepStatus, setStepStatus] = useState<StepStatus>({
    analyze: 'idle', tasks: 'idle', knowledge: 'idle', config: 'idle',
  });
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null);
  const [tasks, setTasks] = useState<GeneratedTask[]>([]);
  // Knowledge files are now generated by templates as part of configFiles
  const [configFiles, setConfigFiles] = useState<{ path: string; content: string }[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [uploadedFiles, setUploadedFiles] = useState<{ name: string; content: string }[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const [isProcessingFiles, setIsProcessingFiles] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const addEntry = () => {
    setEntries(prev => [...prev, { id: crypto.randomUUID(), title: `Section ${prev.length + 1}`, content: "" }]);
  };

  const removeEntry = (id: string) => {
    if (entries.length <= 1) return;
    setEntries(prev => prev.filter(e => e.id !== id));
  };

  const updateEntry = (id: string, field: 'title' | 'content', value: string) => {
    setEntries(prev => prev.map(e => e.id === id ? { ...e, [field]: value } : e));
  };

  const removeUploadedFile = (index: number) => {
    setUploadedFiles(prev => prev.filter((_, i) => i !== index));
  };

  const processFiles = useCallback(async (files: FileList | File[]) => {
    setIsProcessingFiles(true);
    const newFiles: { name: string; content: string }[] = [];

    for (const file of Array.from(files)) {
      const ext = file.name.split('.').pop()?.toLowerCase();
      if (!ext || !['md', 'txt', 'text', 'markdown', 'doc', 'docx', 'csv', 'json', 'yaml', 'yml', 'xml', 'html', 'htm'].includes(ext)) {
        toast({
          title: "Unsupported file",
          description: `"${file.name}" is not a supported text file. Use .md, .txt, .doc, .docx, .csv, .json, .yaml, .xml, or .html files.`,
          variant: "destructive",
        });
        continue;
      }

      // For .doc/.docx we read as text (best effort) — binary docs won't parse perfectly
      // but most modern .docx saved as plain text or markdown will work
      try {
        const text = await file.text();
        if (text.trim()) {
          newFiles.push({ name: file.name, content: text });
        }
      } catch {
        toast({
          title: "Failed to read file",
          description: `Could not read "${file.name}". Try converting it to .md or .txt first.`,
          variant: "destructive",
        });
      }
    }

    if (newFiles.length > 0) {
      setUploadedFiles(prev => [...prev, ...newFiles]);
      // Also add as brain dump entries
      setEntries(prev => [
        ...prev,
        ...newFiles.map(f => ({
          id: crypto.randomUUID(),
          title: f.name.replace(/\.[^.]+$/, ''),
          content: f.content,
        })),
      ]);
      toast({
        title: `${newFiles.length} file${newFiles.length > 1 ? 's' : ''} imported`,
        description: "File contents added as brain dump sections.",
      });
    }
    setIsProcessingFiles(false);
  }, [toast]);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files.length > 0) {
      processFiles(e.dataTransfer.files);
    }
  }, [processFiles]);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const brainDumpText = entries.map(e => `## ${e.title}\n${e.content}`).join('\n\n');

  // Build a minimal fallback analysis from project name/description
  const buildFallbackAnalysis = (): AnalysisResult => {
    const moduleName = projectName.replace(/[^a-zA-Z0-9 ]/g, '').trim() || 'Core';
    const slug = moduleName.toLowerCase().replace(/\s+/g, '-');
    return {
      projectName: projectName || 'Untitled Project',
      description: projectDesc || 'A new project',
      stack: { ...DEFAULT_STACK, framework: 'React', language: 'TypeScript', buildTool: 'Vite', backend: 'Supabase', ui: 'shadcn/ui', stateManagement: 'TanStack Query', forms: 'react-hook-form', validation: 'zod' },
      entities: [slug.replace(/-/g, '_')],
      sharedConcerns: ['auth'],
      modules: [{
        name: moduleName,
        description: projectDesc || `Main module for ${moduleName}`,
        route: `/${slug}`,
        entities: [slug.replace(/-/g, '_')],
        actions: [`Create ${moduleName}`, `List ${moduleName}`, `Update ${moduleName}`, `Delete ${moduleName}`],
        relatedModules: [],
      }],
      phases: [
        { number: 1, name: 'Foundation', description: 'Setup project structure, database, and auth' },
        { number: 2, name: 'Core Features', description: `Build ${moduleName} CRUD and core UI` },
        { number: 3, name: 'Polish', description: 'Testing, error handling, and deployment' },
      ],
    };
  };

  // Step 2: Analyze brain dump
  const handleAnalyze = async () => {
    setStep(2);
    setError(null);
    setStepStatus(prev => ({ ...prev, analyze: 'loading' }));

    try {
      const result = await analyzeProject(projectName, projectDesc, brainDumpText);
      const normalizedResult: AnalysisResult = {
        ...result,
        stack: {
          framework: result.stack?.framework ?? DEFAULT_STACK.framework,
          language: result.stack?.language ?? DEFAULT_STACK.language,
          buildTool: result.stack?.buildTool ?? DEFAULT_STACK.buildTool,
          backend: result.stack?.backend ?? DEFAULT_STACK.backend,
          ui: result.stack?.ui ?? DEFAULT_STACK.ui,
          stateManagement: result.stack?.stateManagement ?? DEFAULT_STACK.stateManagement,
          forms: result.stack?.forms ?? DEFAULT_STACK.forms,
          validation: result.stack?.validation ?? DEFAULT_STACK.validation,
        },
        entities: result.entities || [],
        modules: result.modules || [],
        phases: result.phases || [],
      };

      // If AI returned empty results, use fallback instead of failing
      if (normalizedResult.modules.length === 0 && normalizedResult.entities.length === 0) {
        console.warn("AI returned empty analysis, using fallback");
        const fallback = buildFallbackAnalysis();
        setAnalysis(fallback);
        setStepStatus(prev => ({ ...prev, analyze: 'done' }));
        toast({ title: "Basic analysis generated", description: "AI couldn't extract details — a basic structure was created from your project name. You can retry or proceed." });
        return;
      }

      setAnalysis(normalizedResult);
      setStepStatus(prev => ({ ...prev, analyze: 'done' }));
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Analysis failed";
      setError(msg);
      setStepStatus(prev => ({ ...prev, analyze: 'error' }));
      toast({ title: "Analysis failed", description: msg, variant: "destructive" });
    }
  };

  // Step 3: Generate tasks, then build entire framework from templates
  const handleGenerate = async () => {
    if (!analysis) return;
    setStep(3);
    setError(null);

    // Generate tasks (AI call — creative work)
    setStepStatus(prev => ({ ...prev, tasks: 'loading' }));
    let taskResult: GeneratedTask[];
    try {
      taskResult = await generateTasks(analysis);
      setTasks(taskResult);
      setStepStatus(prev => ({ ...prev, tasks: 'done' }));
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Task generation failed";
      setError(msg);
      setStepStatus(prev => ({ ...prev, tasks: 'error' }));
      toast({ title: "Task generation failed", description: msg, variant: "destructive" });
      return;
    }

    // Generate entire framework deterministically from templates (no AI call)
    // This produces everything: config files, knowledge files (skills, tools,
    // workflows, indexes), strategic docs, task tracker UI, and more.
    setStepStatus(prev => ({ ...prev, knowledge: 'loading' }));
    try {
      const allFiles = generateConfigFromTemplates(analysis, taskResult);
      setConfigFiles(allFiles);
      setStepStatus(prev => ({ ...prev, knowledge: 'done', config: 'done' }));
    } catch (e) {
      const msg = e instanceof Error ? e.message : "Framework generation failed";
      setError(msg);
      setStepStatus(prev => ({ ...prev, knowledge: 'error' }));
      toast({ title: "Framework generation failed", description: msg, variant: "destructive" });
      return;
    }
  };

  // Step 4: Save and navigate
  const handleSave = async () => {
    if (!analysis) return;

    const stack: Project['stack'] = analysis.stack ?? DEFAULT_STACK;

    const phases = analysis.phases.map(p => ({
      id: crypto.randomUUID(),
      number: p.number,
      name: p.name,
      description: p.description,
      status: 'pending' as const,
    }));

    const projectTasks = tasks.map(t => ({
      taskCode: t.task_code,
      title: t.title,
      description: t.description,
      phase: t.phase,
      category: t.category as any,
      assignedTo: t.assigned_to,
      priority: t.priority,
      xpReward: t.xp_reward,
      status: 'pending' as const,
      progressPct: 0,
      dependencies: t.dependencies || [],
      watReferences: t.wat_references || [],
    }));

    // Extract knowledge files from the unified output for the project model
    const projectKnowledgeFiles = configFiles
      .filter(f => f.path.startsWith('knowledge/'))
      .map(f => ({
        path: f.path,
        type: (f.path.includes('/skills/') || f.path.endsWith('.skill.md') ? 'skill'
          : f.path.includes('/tools/') || f.path.endsWith('.tool.md') ? 'tool'
          : f.path.includes('/workflows/') || f.path.endsWith('.workflow.md') ? 'workflow'
          : f.path === 'knowledge/skills.md' || f.path === 'knowledge/tools.md' || f.path === 'knowledge/workflows.md' ? 'index'
          : 'config') as any,
        content: f.content,
      }));

    const allGeneratedFiles = configFiles.map(f => ({ path: f.path, content: f.content }));

    try {
      const project = store.createProject(
        analysis.projectName || projectName,
        analysis.description || projectDesc,
        stack
      );
      project.phases = phases;
      project.tasks = projectTasks;
      project.knowledgeFiles = projectKnowledgeFiles;
      project.generatedFiles = allGeneratedFiles;
      store.saveProject(project);

      // Auto-seed tasks to the tracker
      const supabaseTasks = projectTasks.map(t => ({
        task_code: t.taskCode,
        title: t.title,
        description: t.description,
        phase: t.phase,
        category: t.category,
        assigned_to: t.assignedTo,
        status: t.status as 'pending' | 'in_progress' | 'completed' | 'blocked',
        priority: t.priority,
        progress_pct: t.progressPct,
        xp_reward: t.xpReward,
        dependencies: t.dependencies,
        wat_references: t.watReferences,
        started_at: null,
        completed_at: null,
        notes: null,
        project_id: project.id,
      }));
      seedTasks(supabaseTasks).catch(() => {});

      navigate(`/projects/${project.id}`);
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Failed to save project';
      toast({ title: 'Save failed', description: msg, variant: 'destructive' });
    }
  };

  const stepLabels = ['Brain Dump', 'Analyze', 'Generate', 'Review'];

  const StatusIcon = ({ status }: { status: string }) => {
    if (status === 'loading') return <Loader2 className="h-4 w-4 animate-spin text-primary" />;
    if (status === 'done') return <Check className="h-4 w-4 text-accent" />;
    if (status === 'error') return <AlertCircle className="h-4 w-4 text-destructive" />;
    return <div className="h-4 w-4 rounded-full border border-muted-foreground/30" />;
  };

  return (
    <div className="mx-auto max-w-3xl p-6 lg:p-8">
      <div className="mb-8">
        <h1 className="font-display text-2xl font-bold">New Project</h1>
        <p className="text-muted-foreground">Dump your ideas, AI generates a complete framework.</p>
      </div>

      {/* Step indicator */}
      <div className="mb-8 flex items-center gap-3">
        {stepLabels.map((label, i) => (
          <div key={i} className="flex items-center gap-2">
            <div className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold ${
              step > i + 1 ? 'bg-accent/20 text-accent' :
              step === i + 1 ? 'gradient-primary text-primary-foreground' : 'bg-muted text-muted-foreground'
            }`}>
              {step > i + 1 ? <Check className="h-4 w-4" /> : i + 1}
            </div>
            <span className={`text-sm ${step >= i + 1 ? 'font-medium' : 'text-muted-foreground'}`}>
              {label}
            </span>
            {i < 3 && <div className="h-px w-8 bg-border" />}
          </div>
        ))}
      </div>

      {/* Step 1: Brain Dump */}
      {step === 1 && (
        <div className="space-y-6">
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <label className="text-sm font-medium">Project Name</label>
              <Input value={projectName} onChange={e => setProjectName(e.target.value)} placeholder="My Awesome Project" className="mt-1" />
            </div>
            <div>
              <label className="text-sm font-medium">Brief Description</label>
              <Input value={projectDesc} onChange={e => setProjectDesc(e.target.value)} placeholder="What does this project do?" className="mt-1" />
            </div>
          </div>

          {/* File Upload Drop Zone */}
          <div
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onClick={() => fileInputRef.current?.click()}
            className={`relative cursor-pointer rounded-xl border-2 border-dashed p-8 text-center transition-all ${
              isDragging
                ? 'border-primary bg-primary/5 scale-[1.01]'
                : 'border-muted-foreground/25 hover:border-primary/50 hover:bg-muted/30'
            }`}
          >
            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept=".md,.txt,.text,.markdown,.doc,.docx,.csv,.json,.yaml,.yml,.xml,.html,.htm"
              className="hidden"
              onChange={e => {
                if (e.target.files?.length) {
                  processFiles(e.target.files);
                  e.target.value = '';
                }
              }}
            />
            {isProcessingFiles ? (
              <div className="flex flex-col items-center gap-2">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-sm font-medium">Processing files...</p>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-2">
                <Upload className="h-8 w-8 text-muted-foreground" />
                <p className="text-sm font-medium">Drop files here or click to upload</p>
                <p className="text-xs text-muted-foreground">
                  .md, .txt, .doc, .docx, .csv, .json, .yaml, .xml, .html
                </p>
              </div>
            )}
          </div>

          {/* Uploaded file chips */}
          {uploadedFiles.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {uploadedFiles.map((f, i) => (
                <Badge key={i} variant="secondary" className="gap-1.5 pl-2 pr-1 py-1">
                  <FileText className="h-3 w-3" />
                  <span className="text-xs max-w-[150px] truncate">{f.name}</span>
                  <button
                    onClick={() => removeUploadedFile(i)}
                    className="ml-0.5 rounded-full p-0.5 hover:bg-destructive/20 hover:text-destructive transition-colors"
                  >
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              ))}
            </div>
          )}

          {entries.map((entry) => (
            <Card key={entry.id}>
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <Input
                    value={entry.title}
                    onChange={e => updateEntry(entry.id, 'title', e.target.value)}
                    className="h-8 w-48 text-sm font-medium border-none p-0 shadow-none focus-visible:ring-0"
                  />
                  {entries.length > 1 && (
                    <Button variant="ghost" size="icon" onClick={() => removeEntry(entry.id)} className="h-7 w-7 text-muted-foreground hover:text-destructive">
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={entry.content}
                  onChange={e => updateEntry(entry.id, 'content', e.target.value)}
                  placeholder="Paste your ideas, feature lists, entity descriptions, technical notes..."
                  className="min-h-[150px] font-mono text-sm resize-y"
                />
              </CardContent>
            </Card>
          ))}

          <div className="flex items-center gap-3">
            <Button variant="outline" onClick={addEntry} className="gap-2">
              <Plus className="h-4 w-4" /> Add Section
            </Button>
          </div>

          <div className="flex justify-end">
            <Button
              onClick={handleAnalyze}
              disabled={!projectName.trim() || entries.every(e => !e.content.trim())}
              className="gap-2"
            >
              <Sparkles className="h-4 w-4" /> Analyze with AI <ArrowRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      )}

      {/* Step 2: Analysis Review */}
      {step === 2 && (
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <div className="flex items-center gap-3">
                <StatusIcon status={stepStatus.analyze} />
                <CardTitle className="font-display">
                  {stepStatus.analyze === 'loading' ? 'Analyzing your brain dump...' :
                   stepStatus.analyze === 'done' ? 'Analysis Complete' :
                   stepStatus.analyze === 'error' ? 'Analysis Failed' : 'Analyzing...'}
                </CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              {stepStatus.analyze === 'loading' && (
                <p className="text-sm text-muted-foreground">AI is reading your brain dump, extracting entities, modules, and project structure...</p>
              )}
              {stepStatus.analyze === 'error' && (
                <div className="space-y-3">
                  <p className="text-sm text-destructive">{error}</p>
                  <div className="flex gap-2">
                    <Button variant="outline" onClick={() => { setStep(1); setStepStatus(prev => ({ ...prev, analyze: 'idle' })); }}>
                      <ArrowLeft className="h-4 w-4 mr-2" /> Back to Edit
                    </Button>
                    <Button onClick={handleAnalyze} className="gap-2">
                      <Sparkles className="h-4 w-4" /> Retry Analysis
                    </Button>
                  </div>
                </div>
              )}
              {stepStatus.analyze === 'done' && analysis && (
                <div className="space-y-4">
                  <div>
                    <span className="text-sm font-medium">Project:</span>{" "}
                    <span className="font-display font-semibold">{analysis.projectName}</span>
                  </div>
                  <div>
                    <span className="text-sm font-medium">Stack:</span>{" "}
                    <span className="text-sm text-muted-foreground">{analysis?.stack?.framework ?? 'N/A'} + {analysis?.stack?.language ?? 'N/A'} + {analysis?.stack?.backend ?? 'N/A'}</span>
                  </div>
                  <div>
                    <span className="text-sm font-medium">Modules ({analysis.modules.length}):</span>
                    <div className="mt-2 flex flex-wrap gap-2">
                      {analysis.modules.map((m, i) => (
                        <Badge key={i} variant="secondary">{m.name}</Badge>
                      ))}
                    </div>
                  </div>
                  <div>
                    <span className="text-sm font-medium">Entities ({analysis.entities.length}):</span>
                    <div className="mt-2 flex flex-wrap gap-2">
                      {analysis.entities.map((e, i) => (
                        <Badge key={i} variant="outline" className="font-mono text-xs">{e}</Badge>
                      ))}
                    </div>
                  </div>
                  <div>
                    <span className="text-sm font-medium">Phases ({analysis.phases.length}):</span>
                    <div className="mt-2 space-y-1">
                      {analysis.phases.map((p, i) => (
                        <div key={i} className="text-sm text-muted-foreground">
                          <span className="font-medium text-foreground">Phase {p.number}:</span> {p.name} — {p.description}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {stepStatus.analyze === 'done' && (
            <div className="flex justify-between">
              <Button variant="outline" onClick={() => { setStep(1); setStepStatus(prev => ({ ...prev, analyze: 'idle' })); }} className="gap-2">
                <ArrowLeft className="h-4 w-4" /> Back
              </Button>
              <Button onClick={handleGenerate} className="gap-2 glow-primary">
                <Sparkles className="h-4 w-4" /> Generate Framework <ArrowRight className="h-4 w-4" />
              </Button>
            </div>
          )}
        </div>
      )}

      {/* Step 3: Generation Progress */}
      {step === 3 && (
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="font-display">Generating Framework</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {[
                { key: 'tasks' as const, label: 'Task Generation', desc: 'AI generates tasks with dependencies and priorities' },
                { key: 'knowledge' as const, label: 'Framework Generation', desc: 'Building knowledge files, config, strategic docs, and UI code' },
                { key: 'config' as const, label: 'Complete', desc: 'All files generated — ready for review' },
              ].map(({ key, label, desc }) => (
                <div key={key} className="flex items-start gap-3 p-3 rounded-lg bg-muted/50">
                  <StatusIcon status={stepStatus[key]} />
                  <div>
                    <p className="text-sm font-medium">{label}</p>
                    <p className="text-xs text-muted-foreground">{desc}</p>
                    {key === 'tasks' && stepStatus.tasks === 'done' && (
                      <p className="text-xs text-accent mt-1">{tasks.length} tasks generated</p>
                    )}
                    {key === 'knowledge' && stepStatus.knowledge === 'done' && (
                      <p className="text-xs text-accent mt-1">{configFiles.filter(f => f.path.startsWith('knowledge/')).length} knowledge files generated</p>
                    )}
                    {key === 'config' && stepStatus.config === 'done' && (
                      <p className="text-xs text-accent mt-1">{configFiles.length} total files generated</p>
                    )}
                  </div>
                </div>
              ))}

              {error && (
                <div className="p-3 rounded-lg bg-destructive/10 text-sm text-destructive">
                  {error}
                </div>
              )}
            </CardContent>
          </Card>

          {stepStatus.config === 'done' && (
            <div className="flex justify-end">
              <Button onClick={() => setStep(4)} className="gap-2">
                Review & Save <ArrowRight className="h-4 w-4" />
              </Button>
            </div>
          )}

          {(stepStatus.tasks === 'error' || stepStatus.knowledge === 'error' || stepStatus.config === 'error') && (
            <div className="flex justify-between">
              <Button variant="outline" onClick={() => { setStep(2); setError(null); }} className="gap-2">
                <ArrowLeft className="h-4 w-4" /> Back
              </Button>
              <Button variant="outline" onClick={handleGenerate} className="gap-2">
                Retry Generation
              </Button>
            </div>
          )}
        </div>
      )}

      {/* Step 4: Review & Save */}
      {step === 4 && (
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="font-display">Review Generated Output</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="p-3 rounded-lg bg-muted/50">
                  <p className="text-2xl font-bold font-display">{tasks.length}</p>
                  <p className="text-xs text-muted-foreground">Tasks</p>
                </div>
                <div className="p-3 rounded-lg bg-muted/50">
                  <p className="text-2xl font-bold font-display">{configFiles.filter(f => f.path.startsWith('knowledge/')).length}</p>
                  <p className="text-xs text-muted-foreground">Knowledge Files</p>
                </div>
                <div className="p-3 rounded-lg bg-muted/50">
                  <p className="text-2xl font-bold font-display">{configFiles.length}</p>
                  <p className="text-xs text-muted-foreground">Total Files</p>
                </div>
                <div className="p-3 rounded-lg bg-muted/50">
                  <p className="text-2xl font-bold font-display">{analysis?.modules.length || 0}</p>
                  <p className="text-xs text-muted-foreground">Modules</p>
                </div>
              </div>

              <div>
                <p className="text-sm font-medium mb-2">Generated Files:</p>
                <ScrollArea className="h-[200px]">
                  <div className="space-y-1">
                    {configFiles.map((f, i) => (
                      <div key={i} className="text-xs font-mono text-muted-foreground py-0.5">
                        {f.path}
                      </div>
                    ))}
                  </div>
                </ScrollArea>
              </div>
            </CardContent>
          </Card>

          <div className="flex justify-between">
            <Button variant="outline" onClick={() => setStep(3)} className="gap-2">
              <ArrowLeft className="h-4 w-4" /> Back
            </Button>
            <Button onClick={handleSave} className="gap-2 glow-primary">
              <Sparkles className="h-4 w-4" /> Save Project
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
